"""Create resume history table

Revision ID: 4d4f87b1027f
Revises: 38a54e0fbbf2
Create Date: 2025-09-02 12:43:38.019423

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.sql import func

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d4f87b1027f"
down_revision: Union[str, None] = "38a54e0fbbf2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resume_history",
        sa.Column("original_content", sa.Text(), nullable=False),
        sa.Column("improved_content", sa.Text(), nullable=False),
        sa.Column(
            "timestamp",
            sa.TIMESTAMP(),
            nullable=False,
            server_default=func.now(),
        ),
        sa.Column("resume_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["resume_id"], ["resumes.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resume_history")
    # ### end Alembic commands ###
